Project-Trofos/trofos

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/pull_request_template.md, README.md
Add templates for issue creation- [see here:](https://github.com/bokuanT/trofos/issues/new/choose)
Add template for PRs
=> Add PR, bug report and feature request workflow/ template

packages/backend/prisma/actionsOnRoles.seed.ts, packages/backend/prisma/migrations/20240904053503_add_action_update_project_users/migration.sql, packages/backend/prisma/migrations/20240904081045_insert_update_project_users_actions_on_roles/migration.sql, packages/backend/prisma/role.seed.ts, packages/backend/prisma/schema.prisma, packages/backend/src/routes/project.route.ts, packages/frontend/src/components/modals/__snapshots__/BulkProjectCreationModal.test.tsx.snap, packages/frontend/src/components/tables/UserTable.test.tsx, packages/frontend/src/components/tables/UserTable.tsx, packages/frontend/src/components/tables/__snapshots__/UserTable.test.tsx.snap, packages/frontend/src/helpers/constants.ts, packages/frontend/src/pages/coursePages/CoursePeople.tsx, packages/frontend/src/pages/projectPages/Project.tsx, packages/frontend/src/pages/projectPages/ProjectPeople.tsx
T3-16
- Add new permission for faculty/admin to delete user from project on backend
- Add frontend authz check, hide remove button and disable change course-role modal (becomes view only) if no permission
- Old:
- New:
- Hide id in user table for project people / course people if user is not admin/faculty
- New:
- Disable dettach/ attach project to course button for those without permissions
- Old:
- New:
**Checklist**
=> Hide buttons when user dont have authorization in frontend

packages/frontend/src/components/cards/RetrospectiveContainerCard.tsx, packages/frontend/src/components/cards/RetrospectiveContentCard.tsx, packages/frontend/src/components/modals/BacklogCreationModal.tsx
T3-36
@bokuanT 
Fixed a bug where the "Create Backlog" modal in Retrospective page instead created duplicated backlogs
**Checklist**
=> Fix issue where backlogs were duplicated

packages/frontend/src/api/standup.ts, packages/frontend/src/components/cards/StandUpCard/useStandUpCardMenu.tsx
=> Fix compile error missed out in #132 CI

packages/frontend/src/api/hooks.ts, packages/frontend/src/pages/projectPages/ProjectPeople.tsx
#XX
@bokuanT 
Add 'add user' fallback on project page for users with permissions
**Checklist**
=> Add permission to add user to project

packages/backend/src/controllers/invite.ts, packages/backend/src/services/project.service.ts
#XX
@[Username]
Fix bug on adding user to course multiple times when inviting user to independent project
**Checklist**
=> Fix issue when inviting user to independent project

packages/frontend/src/components/modals/__snapshots__/BacklogCreationModal.test.tsx.snap
=> Update snapshot for failing test

packages/frontend/src/templates/MainLayout.css, packages/frontend/src/templates/MainLayout.tsx
=> Add logo to main layout

packages/frontend/src/components/visualization/BurnDownChart.tsx, packages/frontend/src/components/visualization/useBurndownChart.test.tsx, packages/frontend/src/components/visualization/useBurndownChart.ts
T3-50
@thamruicong 
@[Username]
If there are history changes within the same hour, they are aggregated (if more than 5 changes in same hour, only 5 are shown)
Same logic for history that occur before the start of a sprint
**Checklist**
=> Aggregate changes within hour and before start in burndown

packages/backend/prisma/migrations/20241008161111_add_project_owner_field_for_project/migration.sql, packages/backend/prisma/schema.prisma, packages/backend/src/__tests__/controllers/invite.test.ts, packages/backend/src/__tests__/mocks/csvData.ts, packages/backend/src/__tests__/mocks/inviteData.ts, packages/backend/src/__tests__/mocks/projectData.ts, packages/backend/src/__tests__/services/course.service.test.ts, packages/backend/src/__tests__/services/project.service.test.ts, packages/backend/src/__tests__/services/role.service.test.ts, packages/backend/src/aws/ses.ts, packages/backend/src/controllers/invite.ts, packages/backend/src/services/course.service.ts, packages/backend/src/services/project.service.ts, packages/backend/src/templates/email.ts, packages/frontend/src/api/invite.ts, packages/frontend/src/api/types.ts, packages/frontend/src/components/modals/UserTableRoleManagementModal.tsx, packages/frontend/src/components/modals/confirm.tsx, packages/frontend/src/components/tables/UserTable.tsx, packages/frontend/src/helpers/constants.ts, packages/frontend/src/pages/projectPages/ProjectPeople.tsx
#T3-49
@bokuanT 
According to below workflow:
- Admin/Faculty: Should be able to add student by email - if email exists, directly add, else if email not exists, prompt invite
- Project Owner: Should be able to invite
- Student: No actions
Added tag to display project owner
Project owner field is optional for backwards compatibility (subsequent project creations will have owners)
Update invite email template body (subject is the same)
Old
New
**Checklist**
=> Invite workflow

README.md, monitoring/.env.example, monitoring/README.md, monitoring/docker-compose-monitoring.yml, monitoring/grafana/provisioning/dashboards/postgres_dashboard.json, monitoring/prometheus/prometheus.yml
T3-51
@[Username]
T3-51 Update readme with .env instructions, add postgres monitoring and dashboards
**Checklist**
=> T3-51 Update readme with .env instructions, add postgres monitoring and dashboards

monitoring/.env.example, monitoring/README.md, monitoring/docker-compose-monitoring.yml, monitoring/grafana/provisioning/alerting/alert_resources.yml, monitoring/grafana/provisioning/alerting/alert_rules.yml
T3-68
@thamruicong 
Integrate grafana alerting for when backend restarts/ has stopped, CPU usage is high, RAM usage is high and if disk space used is high
**Checklist**
=> Add alerting to telegram for grafana

packages/backend/package.json, packages/backend/pnpm-lock.yaml, packages/backend/src/__tests__/controllers/invite.test.ts, packages/backend/src/aws/ses.ts, packages/backend/src/controllers/comment.ts, packages/backend/src/controllers/invite.ts, packages/backend/src/templates/email.ts, packages/frontend/src/components/modals/confirm.tsx, packages/frontend/src/pages/projectPages/ProjectPeople.tsx
T3-62
@bokuanT 
- Fix bug `"Template name <TROFOS_INVITE_https://trofos.comp.nus.edu.sg>: only alphanumeric ASCII characters, '_', and '-' are allowed."}}` due to invalid template name
- Update to more reliable SendGrid ESP (sends semi-instantaneously)
- Fix bug where tokens are not deleted when email fails to send
- Add additional prompt to inform user that email does not exist
Will need to update env upon staging deployment
**Checklist**
=> Invite bug fix

monitoring/prometheus/prometheus.yml
=> Update backend monitoring port

docker-compose-deploy.yml, docker-compose-production.yml
=> Update docker compose env vars

packages/backend/package.json, packages/backend/pnpm-lock.yaml, packages/backend/src/routes/account.route.ts, packages/backend/src/server.ts
=> Fix SAMLResponse not found

packages/backend/prisma/migrations/20250123081052_add_archive_course/migration.sql, packages/backend/prisma/schema.prisma, packages/backend/src/__tests__/controllers/course.test.ts, packages/backend/src/__tests__/mocks/courseData.ts, packages/backend/src/__tests__/services/course.service.test.ts, packages/backend/src/__tests__/services/project.service.test.ts, packages/backend/src/controllers/course.ts, packages/backend/src/routes/course.route.ts, packages/backend/src/services/course.service.ts, packages/frontend/src/api/course.ts, packages/frontend/src/api/hooks.ts, packages/frontend/src/api/types.ts, packages/frontend/src/components/cards/CourseCard.test.tsx, packages/frontend/src/components/cards/CourseCard.tsx, packages/frontend/src/components/cards/ProjectCard.test.tsx, packages/frontend/src/components/cards/__snapshots__/ProjectCard.test.tsx.snap, packages/frontend/src/components/modals/BulkProjectCreationModal.test.tsx, packages/frontend/src/components/modals/ImportDataModal.test.tsx, packages/frontend/src/components/modals/confirm.tsx, packages/frontend/src/components/tables/CourseTable.test.tsx, packages/frontend/src/mocks/handlers.ts
=> Add course archiving

packages/frontend/package.json, packages/frontend/pnpm-lock.yaml
=> update vitest to fix CI bug

packages/backend/src/services/csv.service.ts, packages/backend/src/services/types/csv.service.types.ts, packages/frontend/src/pages/Invite.tsx, packages/frontend/src/pages/Register.tsx
=> Integrate sso to batch upload

packages/backend/src/controllers/account.ts, packages/backend/src/helpers/error/assertions.ts, packages/backend/src/helpers/ssoHelper.ts, packages/backend/src/routes/account.route.ts
#XX
@bokuanT 
Use relayState to keep track of state of SAML response, which will differentiate between student and staff SSO
**Checklist**
=> Attempt to fix staff SSO bug

packages/backend/prisma/migrations/20250203132004_add_archive_proj_permissions/migration.sql, packages/backend/prisma/migrations/20250203133032_insert_add_archive/migration.sql, packages/backend/prisma/role.seed.ts, packages/backend/prisma/schema.prisma, packages/backend/src/middleware/auth.middleware.ts, packages/backend/src/routes/project.route.ts, packages/backend/src/services/ai.service.ts, packages/frontend/src/helpers/error.ts
#XX
@thamruicong 
**Checklist**
=> Dont allow students to delete/ archive non-independent projects and add err handling for AI

packages/frontend/Dockerfile.production
=> Test actions

.github/workflows/e2e-tests.yaml, .github/workflows/pull-request-ci.yaml, packages/backend/prisma/migrations/20250204123325_add_feature_flag/migration.sql, packages/backend/prisma/migrations/20250204123634_add_ug_copilot_feature_flag/migration.sql, packages/backend/prisma/schema.prisma, packages/backend/src/controllers/featureFlag.ts, packages/backend/src/middleware/feature_flag.middleware.ts, packages/backend/src/routes/ai.route.ts, packages/backend/src/routes/featureFlag.route.ts, packages/backend/src/server.ts, packages/backend/src/services/featureFlag.service.ts, packages/frontend/src/api/featureFlag.ts, packages/frontend/src/api/types.ts, packages/frontend/src/templates/MainLayout.tsx, packages/hocus_pocus_server/package.json
@thamruicong 
Introduce feature flag design pattern, to easily disable features during run time
in db, new table to track feature flags, with a col for feature name and another for active status
in backend- use checkFeatureFlag middlware
in  frontend- query for allFeatureFlags and check that for the active field after you find your featureFlag obj by feature name
**Checklist**
=> Add feature flags api and enable for RAG

packages/backend/src/controllers/featureFlag.ts, packages/backend/src/controllers/requestTypes.ts, packages/backend/src/routes/featureFlag.route.ts, packages/backend/src/server.ts, packages/backend/src/services/featureFlag.service.ts, packages/frontend/src/api/featureFlag.ts, packages/frontend/src/api/index.ts, packages/frontend/src/components/cards/SprintListingCard.tsx, packages/frontend/src/components/tabs/FeatureFlagManagement.tsx, packages/frontend/src/pages/Admin.tsx
=> Fix buggy sprint notes tour popup

packages/backend/prisma/migrations/20250207021426_add_sso_login_feature_enum/migration.sql, packages/backend/prisma/migrations/20250207021457_add_sso_login_feature_flag/migration.sql, packages/backend/prisma/schema.prisma, packages/backend/src/__tests__/controllers/account.test.ts, packages/backend/src/routes/account.route.ts, packages/backend/src/services/authentication.service.ts, packages/frontend/src/app/App.tsx, packages/frontend/src/components/tour/Tour.tsx, packages/frontend/src/components/tour/TourButton.tsx, packages/frontend/src/components/tour/TourProvider.tsx, packages/frontend/src/components/tour/TourSteps.tsx, packages/frontend/src/pages/FacultyDashboard.tsx, packages/frontend/src/pages/Login.tsx, packages/frontend/src/pages/UserDashboard.tsx
#XX
@[Username]
- Add sso login to feature flag
- Add tests for processSAMLResponse
- Add tour button in dashboard
**Checklist**
=> Minor fixes

packages/backend/src/__tests__/services/authentication.service.test.ts, packages/backend/src/helpers/ssoHelper.ts, packages/backend/src/services/authentication.service.ts
=> update staff sso attributes

packages/ai_insight_worker/src/insights/backlogInsights.ts, packages/ai_insight_worker/src/insights/contributionInsight.ts, packages/ai_insight_worker/src/insights/scrumCeremoniesInsights.ts, packages/ai_insight_worker/src/service/backlog.ts, packages/ai_insight_worker/src/service/contribution.ts, packages/ai_insight_worker/src/service/index.ts, packages/ai_insight_worker/src/service/scrumCeremonies.ts, packages/backend/src/controllers/course.ts, packages/backend/src/routes/course.route.ts, packages/backend/src/services/course.service.ts, packages/backend/src/services/sprint.service.ts, packages/common/README.md, packages/frontend/src/api/course.ts, packages/frontend/src/api/index.ts, packages/frontend/src/api/types.ts, packages/frontend/src/components/cards/CourseRetrospectiveInsightHubCard.tsx, packages/frontend/src/components/modals/SprintInsightModal.tsx, packages/frontend/src/helpers/dateFormatter.ts, packages/frontend/src/pages/coursePages/CourseStatistics.tsx
#XX
@thamruicong 
Add UI in course to see all latest available sprint insights in a course, for all projects
Add refactor sprint insight generation code, add 1 more category of insights (Scrum ceremonies evaluation)
**Checklist**
=> Add course page to see all projects' insights of a course, new insight category

packages/ai_insight_worker/package.json, packages/ai_insight_worker/pnpm-lock.yaml, packages/backend/package.json, packages/backend/pnpm-lock.yaml, packages/common/package.json, packages/common/prisma/migrations/20250312170756_update_base_comment_seq/migration.sql, packages/hocus_pocus_server/package.json, packages/hocus_pocus_server/pnpm-lock.yaml
=> fix seq issue

docs/pages/rag_parse_pages/guide_ai.md, docs/pages/rag_parse_pages/guide_course_management.md, docs/pages/rag_parse_pages/guide_ext_api.md, docs/pages/rag_parse_pages/guide_project_management.markdown
=> revert toc markdown

packages/backend/src/controllers/project.ts, packages/frontend/e2e-tests/externalApi.e2e.ts
#XX
@thamruicong 
**Checklist**
=> Fix typo in BE
